within TransiEnt.Grid.Electrical.Noise;
block TypicalLumpedGridError "Typical grid error (derived from frequency measurements via model inversion)"


//________________________________________________________________________________//
// Component of the TransiEnt Library, version: 2.0.1                             //
//                                                                                //
// Licensed by Hamburg University of Technology under the 3-BSD-clause.           //
// Copyright 2021, Hamburg University of Technology.                              //
//________________________________________________________________________________//
//                                                                                //
// TransiEnt.EE, ResiliEntEE, IntegraNet and IntegraNet II are research projects  //
// supported by the German Federal Ministry of Economics and Energy               //
// (FKZ 03ET4003, 03ET4048, 0324027 and 03EI1008).                                //
// The TransiEnt Library research team consists of the following project partners://
// Institute of Engineering Thermodynamics (Hamburg University of Technology),    //
// Institute of Energy Systems (Hamburg University of Technology),                //
// Institute of Electrical Power and Energy Technology                            //
// (Hamburg University of Technology)                                             //
// Fraunhofer Institute for Environmental, Safety, and Energy Technology UMSICHT, //
// Gas- und Wärme-Institut Essen						  //
// and                                                                            //
// XRG Simulation GmbH (Hamburg, Germany).                                        //
//________________________________________________________________________________//




  extends Base.PartialGridError;

    outer SimCenter simCenter;
    parameter SI.Power P_L = simCenter.P_n_low;

  Basics.Tables.GenericDataTable P_Z_UCTE_2012(
    datasource=TransiEnt.Basics.Tables.DataPrivacy.isPublic,
    constantfactor=-P_L,
    relativepath="electricity/TypicalLumpedGridError_ENTSOE_Modeled_60s_2012.txt") "Timeseries generated by inverting the derive grid dynamics model and putting the frequency measurement from 2012 at input" annotation (Placement(transformation(extent={{-36,-40},{44,40}})));
equation

  connect(P_Z_UCTE_2012.y1, y) annotation (Line(points={{48,0},{78,0},{110,0}}, color={0,0,127}));
  annotation (Icon(coordinateSystem(preserveAspectRatio=false, extent={{-100,-100},{100,100}}), graphics={
        Rectangle(
          extent={{-46,64},{4,-56}},
          lineColor={255,255,255},
          fillColor={0,134,134},
          fillPattern=FillPattern.Solid),
        Line(points={{-46,-56},{-46,64},{54,64},{54,-56},{-46,-56},{-46,-26},{54,-26},{54,4},{-46,4},{-46,34},{54,34},{54,64},{4,64},{4,-57}},
            color={0,0,0})}), Diagram(graphics,
                                      coordinateSystem(preserveAspectRatio=false, extent={{-100,-100},{100,100}})));
end TypicalLumpedGridError;
